spring:
  couchbase:
    connection-string: couchbase://localhost
    username: Administrator
    password: password
  data:
    couchbase:
      bucket-name: sms_app
      scope-name: _default
      auto-index: true
  cache:
    type: caffeine
    cache-names: activeLimiterConditions
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=60m

logging:
  level:
    org.springframework.data.couchbase.repository.query: ERROR

security:
  jwt:
    secret-key: 3016c6eb-da39-47b2-8aa4-863e6d48c204
    access-token-expiration: 3600000
    refresh-token-expiration: 86400000
    skipped-endpoints:
      - /api/bo/users/login

app:
  title: Virtual thread based SMS Firewall
  version: @project.version@
  phone-number:
    country-code: +98
  smsc-api:
    url: http://localhost:8083

server:
  port: 8082