name: Build SMS Firewall application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout source
        uses: actions/checkout@v4

      # Step 2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3
      - name: Build with Maven
        run: mvn -B clean verify

      # Step 4
      - name: Package application
        run: mvn -B package -DskipTests

      # Step 5
      - name: Upload the artifact of webflux application
        uses: actions/upload-artifact@v4
        with:
          name: spring-webflux-sms-firewall
          path: spring-webflux-sms-firewall/target/*.jar
